name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        IMAGE_TAG=$(git rev-parse --short HEAD) # Get the short commit SHA
        docker build . --file Dockerfile --tag shivamgutgutia/vcfgenerator:$IMAGE_TAG

    - name: Push Docker image to Docker Hub
      run: docker push shivamgutgutia/vcfgenerator:$IMAGE_TAG
